// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAljSY-pCini8J5Xa-8U9sWjXwYCb6dM',
    appId: '1:698075238579:web:e6fc6a86f448a06dd420c6',
    messagingSenderId: '698075238579',
    projectId: 'asp-final-a7e06',
    authDomain: 'asp-final-a7e06.firebaseapp.com',
    storageBucket: 'asp-final-a7e06.appspot.com',
    measurementId: 'G-86ZG6LWDED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfM_XxclYMJJYqUq9ZdjHDdErs7KJz2dI',
    appId: '1:698075238579:android:aea6f02e83d8aa21d420c6',
    messagingSenderId: '698075238579',
    projectId: 'asp-final-a7e06',
    storageBucket: 'asp-final-a7e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDa-A7qEZTZKkcAIhvXLlpInEhNxKqLTw',
    appId: '1:698075238579:ios:8f2c42beb8106bdbd420c6',
    messagingSenderId: '698075238579',
    projectId: 'asp-final-a7e06',
    storageBucket: 'asp-final-a7e06.appspot.com',
    androidClientId: '698075238579-vngs057jsde153d2pa1duo5q94nsj1dr.apps.googleusercontent.com',
    iosClientId: '698075238579-43lbtoii5flk61jocnebqju3otngncob.apps.googleusercontent.com',
    iosBundleId: 'com.example.aspBase',
  );
}
